[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["node"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
